---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jump
spec:
  template:
    spec:
      containers:
        - name: jump
          image: shokohsc/jump
          env:
            - name: SITES_ENDPOINT_URL
              value: 'http://api.sidekick:3000/api/startpage/jump'
            - name: SHOWCLOCK
              value: 'false'
